project:
  type: website
  output-dir: docs

website:
  title: "OTN Symposium 2024 RSF Workshop"
  navbar:
    left:

    - text: "R & Rstudio"
      href: Rinst.html
    - text: "RSF with RF"
      href: RF.html
    - text: "RSF with GLMM"
      href: GLMM.html

format:
  html:
    theme: yeti
    highlight: haddock
    css: styles.css